version: '3.7'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./:/code
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
  backend:
    build:
      context: ./backend
      dockerfile: DockerfileDeploy
    env_file:
      - backend/.env
    command: sh -c "chmod +x ./backend/entrypoint.sh && ./backend/entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
      build: ./frontend
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      command: npm run dev
      depends_on:
        - backend


volumes:
  static_volume: