services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - static_volume:/app/backend/static
      - ./nginx/development:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - db
      - frontend
  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - ./:/code
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
  backend:
    build:
      context: ./backend
      dockerfile: DockerfileDeploy
    env_file:
      - backend/.env
    command: sh -c "chmod +x ./backend/entrypoint.sh && ./backend/entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend


volumes:
  static_volume: