services:
  nginx:
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 500M
    restart: unless-stopped
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - static_volume:/app/backend/static
      - ./nginx/development:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - db
      - frontend
  redis:
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 500M
    image: redis
    ports:
      - "6379:6379"
  db:
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.4'
          memory: 1500M
    image: postgres
    expose:
      - 5432
    volumes:
      - ./:/code
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
  backend:
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '3.0'
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    command: sh -c "chmod +x ./entrypoint.sh && ./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1500M
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run start
    depends_on:
      - backend


volumes:
  static_volume:
