services:
  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - ./:/code
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
  web:
    build:
      context: .
      dockerfile: DockerfileDeploy
    env_file:
      - .env
    command: sh -c "chmod +x ./entrypointdeploy.sh && ./entrypointdeploy.sh"
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  static_volume: