"""Add fields package and location to item model

Revision ID: 1ece75f9a678
Revises: d14ad8249393
Create Date: 2024-03-20 11:34:48.936027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ece75f9a678'
down_revision: Union[str, None] = 'd14ad8249393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('packages', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('location', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'location')
    op.drop_column('item', 'packages')
    # ### end Alembic commands ###
