"""Default working weekend

Revision ID: 39357d9a037a
Revises: dd1b6ba4c128
Create Date: 2024-03-09 14:29:18.764186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39357d9a037a'
down_revision: Union[str, None] = 'dd1b6ba4c128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
