"""rename colunm

Revision ID: b1f25a7ccf84
Revises: 3e052d2a5223
Create Date: 2024-02-11 10:57:21.055606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f25a7ccf84'
down_revision: Union[str, None] = '3e052d2a5223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.drop_constraint('item_stage_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'stage', ['stage_id'], ['id'], ondelete='SET NULL')
    op.drop_column('item', 'stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('stage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_stage_fkey', 'item', 'stage', ['stage'], ['id'], ondelete='SET NULL')
    op.drop_column('item', 'stage_id')
    # ### end Alembic commands ###
