"""add field time to model item

Revision ID: fdec4d9fa148
Revises: 1ece75f9a678
Create Date: 2024-04-03 11:46:09.263059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdec4d9fa148'
down_revision: Union[str, None] = '1ece75f9a678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('time', sa.TIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'time')
    # ### end Alembic commands ###
