"""Flow null true

Revision ID: 22ce8c253404
Revises: b3c9b0592aaa
Create Date: 2024-02-03 17:07:11.741361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22ce8c253404'
down_revision: Union[str, None] = 'b3c9b0592aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('flow', 'category_autoid',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('item', 'order',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('item', 'origin_item',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('item', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item', 'production_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('item', 'stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('item_flow_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'flow', ['flow_id'], ['id'], ondelete='SET NULL')
    op.alter_column('salesorder', 'order',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('salesorder', 'production_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stage', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('stage', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stage', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('salesorder', 'production_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('salesorder', 'order',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_flow_id_fkey', 'item', 'flow', ['flow_id'], ['id'])
    op.alter_column('item', 'stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item', 'production_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('item', 'flow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item', 'origin_item',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('item', 'order',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('flow', 'category_autoid',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('flow', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
