"""add uniq as one to one for order and item

Revision ID: 3e052d2a5223
Revises: 22ce8c253404
Create Date: 2024-02-06 21:06:24.716666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e052d2a5223'
down_revision: Union[str, None] = '22ce8c253404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'item', ['origin_item'])
    op.create_unique_constraint(None, 'salesorder', ['order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salesorder', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    # ### end Alembic commands ###
