"""casade delet for comments with item

Revision ID: 941ed6e3add6
Revises: fdec4d9fa148
Create Date: 2024-04-26 20:49:08.702271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941ed6e3add6'
down_revision: Union[str, None] = 'fdec4d9fa148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_item_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_item_id_fkey', 'comment', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###
