"""casade delet for comments with item

Revision ID: c420096e50b8
Revises: 941ed6e3add6
Create Date: 2024-04-26 20:51:50.510516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c420096e50b8'
down_revision: Union[str, None] = '941ed6e3add6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
