"""Create tables for profiles app

Revision ID: dd1b6ba4c128
Revises: eed7c03e3985
Create Date: 2024-03-09 12:30:36.429995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1b6ba4c128'
down_revision: Union[str, None] = 'eed7c03e3985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
